#pragma once

#include <cstdint>

// Generates the continuation function and data placeholder with the given ordinal.
#define INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(ordinal) \
    extern "C" void __dyn_specialization_musttail_boilerplate_function_placeholder_##ordinal(); \
    extern "C" void __dyn_specialization_notail_boilerplate_function_placeholder_##ordinal(); \
    extern "C" char __dyn_specialization_data_placeholder_##ordinal[1048576] __attribute__((__aligned__(1)));

// Define continuation fnc and data placeholder holes for the given ordinals.
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(0)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(1)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(2)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(3)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(4)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(5)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(6)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(7)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(8)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(9)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(10)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(11)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(12)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(13)
INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(14)
// INTERNAL_GEN_DECLARATION_FOR_PLACEHOLDER(..)

#define INTERNAL_INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(symbol, ordinal, fn_type) \
    using _BOILERPLATE_FNPTR_PLACEHOLDER_TYPE_##ordinal = fn_type; \
    const _BOILERPLATE_FNPTR_PLACEHOLDER_TYPE_##ordinal BOILERPLATE_FNPTR_PLACEHOLDER_##ordinal = \
        reinterpret_cast<_BOILERPLATE_FNPTR_PLACEHOLDER_TYPE_##ordinal>(&symbol##ordinal);

#define INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(ordinal, fn_type) \
    INTERNAL_INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(__dyn_specialization_musttail_boilerplate_function_placeholder_, ordinal, fn_type)

#define INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(ordinal, fn_type) \
    INTERNAL_INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(__dyn_specialization_notail_boilerplate_function_placeholder_, ordinal, fn_type)

// Declares and defines a variable for a data placeholder.
#define INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(ordinal, constant_type) \
    using _CONSTANT_PLACEHOLDER_TYPE_##ordinal = constant_type; \
    union _UNION_CONSTANT_PLACEHOLDER_TYPE_##ordinal { \
        uint64_t _dummy; \
        _CONSTANT_PLACEHOLDER_TYPE_##ordinal _actual_value; \
    }; \
    const uintptr_t _DONOTUSE_INTERNAL_CONSTANT_PLACEHOLDER_##ordinal = \
        reinterpret_cast<uintptr_t>(__dyn_specialization_data_placeholder_##ordinal); \
    const _CONSTANT_PLACEHOLDER_TYPE_##ordinal CONSTANT_PLACEHOLDER_##ordinal = \
        reinterpret_cast<const _UNION_CONSTANT_PLACEHOLDER_TYPE_##ordinal *>( \
            &_DONOTUSE_INTERNAL_CONSTANT_PLACEHOLDER_##ordinal \
        )->_actual_value

// An array index.
#define INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(ordinal) \
    const uint64_t CONSTANT_PLACEHOLDER_##ordinal = reinterpret_cast<uint64_t>(\
        __dyn_specialization_data_placeholder_##ordinal \
    )

// For the user.
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_0(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(0, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_1(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(1, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_2(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(2, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_3(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(3, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_4(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(4, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_5(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(5, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_6(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(6, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_7(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(7, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_8(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(8, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_9(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(9, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_10(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(10, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_11(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(11, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_12(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(12, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_13(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(13, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_14(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER(14, fn_type)

#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_0_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(0, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_1_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(1, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_2_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(2, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_3_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(3, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_4_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(4, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_5_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(5, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_6_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(6, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_7_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(7, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_8_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(8, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_9_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(9, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_10_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(10, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_11_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(11, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_12_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(12, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_13_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(13, fn_type)
#define DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_14_NO_TAILCALL(fn_type) INTERNAL_DEFINE_BOILERPLATE_FNPTR_PLACEHOLDER_NO_TAILCALL(14, fn_type)

#define DEFINE_CONSTANT_PLACEHOLDER_0(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(0, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_1(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(1, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_2(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(2, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_3(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(3, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_4(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(4, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_5(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(5, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_6(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(6, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_7(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(7, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_8(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(8, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_9(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(9, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_10(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(10, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_11(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(11, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_12(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(12, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_13(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(13, constant_type)
#define DEFINE_CONSTANT_PLACEHOLDER_14(constant_type) INTERNAL_DEFINE_CONSTANT_PLACEHOLDER(14, constant_type)

#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_0 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(0)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_1 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(1)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_2 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(2)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_3 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(3)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_4 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(4)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_5 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(5)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_6 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(6)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_7 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(7)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_8 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(8)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_9 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(9)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_10 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(10)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_11 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(11)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_12 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(12)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_13 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(13)
#define DEFINE_INDEX_CONSTANT_PLACEHOLDER_14 INTERNAL_DEFINE_INDEX_CONSTANT_PLACEHOLDER(14)