#[derive(PartialEq, Eq, Debug)]
pub enum DecodeError {
    InvalidMagicHeader,
    InvalidSpecificationVersion,
    UnexpectedEof,
    MalformedInteger,
    MalformedFloatingPoint,
    InvalidSectionId,
    InvalidFunctionType,
    InvalidValType,
    InvalidFunctionTypeResultCount,
    InvalidSectionOrder,
    InvalidUTF8Name,
    InvalidDesc,
    InvalidElemType,
    InvalidLimitsFlag,
    InvalidMutability,
    InvalidTableCount,
    InvalidMemoryCount,
    InvalidIfThenInstr,
    ExpectedEndOfCtrlInstr,
    InvalidCallIndirectInstr,
    InvalidMemorySizeInstr,
    InvalidMemoryGrowInstr,
    InvalidInstr,
}