use crate::definitions::ValType;

#[derive(PartialEq, Eq, Debug)]
pub enum DecodeError {
    InvalidMagicHeader,
    InvalidSpecificationVersion,
    UnexpectedEof,
    MalformedInteger,
    MalformedFloatingPoint,
    InvalidSectionId,
    InvalidFunctionType,
    InvalidValType,
    InvalidSectionOrder,
    InvalidUTF8Name,
    InvalidImportDesc,
    InvalidExportDesc,
    InvalidElemType,
    InvalidLimitsFlag,
    InvalidMutability,
    InvalidTableCount,
    InvalidMemoryCount,
    InvalidIfThenInstr,
    ExpectedEndOfInstrSeq,
    InvalidCallIndirectInstr,
    InvalidMemorySizeInstr,
    InvalidMemoryGrowInstr,
    InvalidInstr,
    InvalidNonConstExpr,
    InvalidTableIndex,
    InvalidMemoryIndex,
    InvalidFunctionCount,
    MalformedCodeSize,
}

// TODO: remove repetitive variants, some of these do the exact same thing
#[derive(PartialEq, Eq, Debug)]
pub enum ValidateError {
    LimitsMinLargerThanK(u64),
    LimitsMaxLargerThanK,
    LimitsMinLargerThanMax,
    FuncTypeHasMoreThanOneResult,
    ExpectedAtLeastOneControlFrame,
    PoppingOutsideOfControlFrame,
    ExpectedOperandInOpdStack { expect: ValType, actual: ValType },
    StackHeightMismatchAtEnd { expect: usize, actual: usize },
    InvalidInstr,
    LocalDoesntExist{ index: usize },
    LocalSetTypeMismatch{ expect: ValType, actual: ValType },
    GlobalDoesntExist{ index: usize },
    GlobalSetTypeMismatch{ expect: ValType, actual: ValType },
    GlobalMustBeMutable{ index: usize },
    LinearMemoryDoesntExist,
    AlignmentIsLargerThanBitWidth { alignment: u64, num_bytes: u64 },
    InvalidControlFrameIndex { index: usize },
    ExpectedMatchingLabelTypes { expect: Vec<ValType>, actual: Vec<ValType> },
    FunctionDoesntExist{ index: usize },
    NoTableDefined,
    NonConstantInstruction,
    GlobalMustBeImportedInConstExpr { index: usize },
    UndefinedFuncInContext { index: usize },
    UndefinedTableInContext { index: usize },
    UndefinedLinearMemoryInContext { index: usize },
    UndefinedGlobalInContext { index: usize },
    InvalidStartFunction,
    TooManyTables,
    TooManyMems,
    DuplicateExportName { name: String }
}

pub enum ExecuteError {
    UnexpectedStackUnderflow,
    ExpectedValType { expect: ValType, actual: ValType },
    Trapped,
    InvalidTypeIndex,
    InvalidFuncIndex,
    InvalidGlobalIndex,
    InvalidMemAddressIndex,
}